In [35]:
import pandas as pd
import numpy as np
import re

In [37]:
X_train = pd.read_excel("F:\\UOC\\3rd Year\\2nd Sem\\ST 3082 - Statistical Learning I\\Group 4\\Project III\\booking cancellation\\X_train.xlsx")
X_train.head()


hotel  lead_time arrival_date_month  arrival_date_week_number  \
0    City Hotel         44            January                         1   
1    City Hotel         32           February                         9   
2    City Hotel         51              April                        15   
3  Resort Hotel        145             August                        33   
4    City Hotel         12                May                        20   

   arrival_date_day_of_month  stays_in_weekend_nights  stays_in_week_nights  \
0                          1                        1                     0   
1                         26                        1                     2   
2                         12                        0                     1   
3                          8                        1                     2   
4                          8                        2                     0   

   adults  children  babies  ... previous_cancellations  \
0       2         0       0  ...                      0   
1       2         0       0  ...                      0   
2       2         0       0  ...                      0   
3       2         0       0  ...                      0   
4       1         0       0  ...                      0   

  previous_bookings_not_canceled booking_changes deposit_type  \
0                              0               0   No Deposit   
1                              0               0   No Deposit   
2                              0               0   No Deposit   
3                              0               0   No Deposit   
4                              0               0   No Deposit   

   days_in_waiting_list    customer_type     adr  required_car_parking_spaces  \
0                     0  Transient-Party   65.00                            0   
1                     0        Transient   62.00                            0   
2                     0        Transient  108.00                            0   
3                     0        Transient  137.83                            0   
4                     0        Transient  105.00                            0   

  total_of_special_requests  room_mismatch  
0                         0              0  
1                         2              1  
2                         0              0  
3                         0              0  
4                         1              0  

[5 rows x 25 columns]

In [38]:
X_test = pd.read_excel("F:\\UOC\\3rd Year\\2nd Sem\\ST 3082 - Statistical Learning I\\Group 4\\Project III\\booking cancellation\\X_test.xlsx")
X_test.head()


hotel  lead_time arrival_date_month  arrival_date_week_number  \
0    City Hotel         58               June                        27   
1  Resort Hotel          0          September                        40   
2    City Hotel        104              April                        16   
3    City Hotel         25               July                        31   
4  Resort Hotel         25               July                        30   

   arrival_date_day_of_month  stays_in_weekend_nights  stays_in_week_nights  \
0                         27                        1                     1   
1                         30                        0                     1   
2                         15                        2                     2   
3                         29                        0                     1   
4                         24                        2                     6   

   adults  children  babies  ... previous_cancellations  \
0       2         2       0  ...                      0   
1       1         0       0  ...                      0   
2       2         0       0  ...                      0   
3       2         0       0  ...                      0   
4       2         0       0  ...                      0   

  previous_bookings_not_canceled booking_changes deposit_type  \
0                              0               1   No Deposit   
1                              0               0   No Deposit   
2                              0               0   No Deposit   
3                              0               0   No Deposit   
4                              0               0   No Deposit   

   days_in_waiting_list  customer_type    adr  required_car_parking_spaces  \
0                     0      Transient  180.9                            0   
1                     0      Transient  136.0                            1   
2                     0      Transient   76.5                            0   
3                     0      Transient  101.0                            0   
4                     0      Transient  154.0                            0   

  total_of_special_requests  room_mismatch  
0                         2              0  
1                         1              0  
2                         1              0  
3                         1              0  
4                         2              0  

[5 rows x 25 columns]

In [39]:
y_train = pd.read_excel("F:\\UOC\\3rd Year\\2nd Sem\\ST 3082 - Statistical Learning I\\Group 4\\Project III\\booking cancellation\\y_train.xlsx")
y_train.head()


is_canceled
0            0
1            0
2            0
3            0
4            0

In [40]:
y_test = pd.read_excel("F:\\UOC\\3rd Year\\2nd Sem\\ST 3082 - Statistical Learning I\\Group 4\\Project III\\booking cancellation\\y_test.xlsx")
y_test.head()


is_canceled
0            0
1            0
2            1
3            0
4            0

In [41]:
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, accuracy_score


In [47]:
# Month mapping (custom order)
month_map = {
    'January': 1, 'February': 2, 'March': 3, 'April': 4,
    'May': 5, 'June': 6, 'July': 7, 'August': 8,
    'September': 9, 'October': 10, 'November': 11, 'December': 12
}

# Apply the mapping
X_train['arrival_date_month'] = X_train['arrival_date_month'].map(month_map)


In [49]:
label_encoders = {}

for col in X_train.select_dtypes(include='object').columns:
    le = LabelEncoder()
    X_train[col] = le.fit_transform(X_train[col])
    label_encoders[col] = le


In [17]:
X_train.head()

hotel  lead_time  arrival_date_month  arrival_date_week_number  \
0      0         44                   1                         1   
1      0         32                   2                         9   
2      0         51                   4                        15   
3      1        145                   8                        33   
4      0         12                   5                        20   

   arrival_date_day_of_month  stays_in_weekend_nights  stays_in_week_nights  \
0                          1                        1                     0   
1                         26                        1                     2   
2                         12                        0                     1   
3                          8                        1                     2   
4                          8                        2                     0   

   adults  children  babies  ...  previous_cancellations  \
0       2         0       0  ...                       0   
1       2         0       0  ...                       0   
2       2         0       0  ...                       0   
3       2         0       0  ...                       0   
4       1         0       0  ...                       0   

   previous_bookings_not_canceled  booking_changes  deposit_type  \
0                               0                0             0   
1                               0                0             0   
2                               0                0             0   
3                               0                0             0   
4                               0                0             0   

   days_in_waiting_list  customer_type     adr  required_car_parking_spaces  \
0                     0              3   65.00                            0   
1                     0              2   62.00                            0   
2                     0              2  108.00                            0   
3                     0              2  137.83                            0   
4                     0              2  105.00                            0   

   total_of_special_requests  room_mismatch  
0                          0              0  
1                          2              1  
2                          0              0  
3                          0              0  
4                          1              0  

[5 rows x 25 columns]

In [19]:
# Initialize and fit the model
clf = DecisionTreeClassifier()
clf.fit(X_train, y_train)


DecisionTreeClassifier()

In [25]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [27]:
# Evaluate the model (on training data for this example)
y_trpred = clf.predict(X_train)

print("Model Accuracy:", accuracy_score(y_train, y_trpred))
print("\nClassification Report:")
print(classification_report(y_train, y_trpred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_train, y_trpred))

Model Accuracy: 0.9922995304079253

Classification Report:
              precision    recall  f1-score   support

           0       0.99      1.00      0.99     59921
           1       0.99      0.98      0.99     35268

    accuracy                           0.99     95189
   macro avg       0.99      0.99      0.99     95189
weighted avg       0.99      0.99      0.99     95189


Confusion Matrix:
[[59719   202]
 [  531 34737]]


In [57]:
# Encode the categorical columns in X_test using the same label encoders
# Apply the mapping
X_test['arrival_date_month'] = X_test['arrival_date_month'].map(month_map)

for col, le in label_encoders.items():
    if col in X_test:
        X_test[col] = le.transform(X_test[col])

# Make predictions
y_pred = clf.predict(X_test)

# Evaluate
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))


Accuracy: 0.8285150012606102

Classification Report:
               precision    recall  f1-score   support

           0       0.86      0.86      0.86     14951
           1       0.77      0.77      0.77      8847

    accuracy                           0.83     23798
   macro avg       0.82      0.82      0.82     23798
weighted avg       0.83      0.83      0.83     23798



In [75]:
importances = pd.Series(clf.feature_importances_, index=X_train.columns)
print(importances.sort_values(ascending=False).head(10))


deposit_type                 0.237813
lead_time                    0.145405
adr                          0.110414
arrival_date_day_of_month    0.078095
arrival_date_week_number     0.060435
total_of_special_requests    0.056182
stays_in_week_nights         0.042550
market_segment               0.041309
room_mismatch                0.034311
previous_cancellations       0.031053
dtype: float64


In [51]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier

param_grid = {
    'max_depth': [5, 10, 15, 20, None],
    'min_samples_split': [2, 10, 20],
    'min_samples_leaf': [1, 5, 10],
    'criterion': ['gini', 'entropy']
}

grid_search = GridSearchCV(DecisionTreeClassifier(), param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train, y_train)

print("Best Parameters:", grid_search.best_params_)
best_tree = grid_search.best_estimator_


Best Parameters: {'criterion': 'gini', 'max_depth': 20, 'min_samples_leaf': 1, 'min_samples_split': 20}


In [53]:
# Evaluate the model (on training data for this example)
y_trpred = best_tree.predict(X_train)

print("Model Accuracy:", accuracy_score(y_train, y_trpred))
print("\nClassification Report:")
print(classification_report(y_train, y_trpred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_train, y_trpred))

Model Accuracy: 0.873787937681875

Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.93      0.90     59921
           1       0.87      0.78      0.82     35268

    accuracy                           0.87     95189
   macro avg       0.87      0.85      0.86     95189
weighted avg       0.87      0.87      0.87     95189


Confusion Matrix:
[[55634  4287]
 [ 7727 27541]]


In [61]:
# Make predictions
y_pred = best_tree.predict(X_test)

# Evaluate
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.8348180519371375

Classification Report:
               precision    recall  f1-score   support

           0       0.85      0.90      0.87     14951
           1       0.81      0.73      0.77      8847

    accuracy                           0.83     23798
   macro avg       0.83      0.81      0.82     23798
weighted avg       0.83      0.83      0.83     23798


Confusion Matrix:
[[13441  1510]
 [ 2421  6426]]
